# -*- coding: utf-8 -*-
"""disease.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1vAl-fV4pBtj89Rl18ERXzsgVPVROYuAZ
"""

!pip install tensorflow keras matplotlib numpy pandas scikit-learn kagglehub

from google.colab import drive
drive.mount('/content/drive')

import os

DATASET_PATH = "/content/drive/MyDrive/plant_disease/PlantVillage"
print(os.listdir(DATASET_PATH))

import os

classes = os.listdir(DATASET_PATH)
num_classes = len(classes)
total_images = 0
for cls in classes:
    total_images += len(os.listdir(os.path.join(DATASET_PATH, cls)))

print("Total Images:", total_images)
print("Number of classes:", num_classes)
print("Sample classes:", classes[:10])

from collections import Counter

class_counts = {}

for cls in classes:
    cls_path = os.path.join(DATASET_PATH, cls)
    class_counts[cls] = len(os.listdir(cls_path))

for i, (k, v) in enumerate(class_counts.items()):
    if i < 16:
        print(k, ":", v)

import matplotlib.pyplot as plt
from PIL import Image
import random

plt.figure(figsize=(10, 10))

for i in range(9):
    cls = random.choice(classes)
    img_name = random.choice(os.listdir(os.path.join(DATASET_PATH, cls)))
    img_path = os.path.join(DATASET_PATH, cls, img_name)

    img = Image.open(img_path)
    plt.subplot(3, 3, i+1)
    plt.imshow(img)
    plt.title(cls)
    plt.axis("off")

plt.show()

import pandas as pd
class_counts = {}

for cls in classes:
    cls_path = os.path.join(DATASET_PATH, cls)
    class_counts[cls] = len(os.listdir(cls_path))

# Convert to DataFrame for better view
df = pd.DataFrame(class_counts.items(), columns=["Class", "Image_Count"])
df.head()

plt.figure(figsize=(12, 6))
plt.bar(df["Class"], df["Image_Count"])
plt.xticks(rotation=90)
plt.xlabel("Disease Class")
plt.ylabel("Number of Images")
plt.title("Class Distribution of PlantVillage Dataset")
plt.show()

sample_class = classes[0]
sample_image = os.listdir(os.path.join(DATASET_PATH, sample_class))[0]
img_path = os.path.join(DATASET_PATH, sample_class, sample_image)

img = Image.open(img_path)
print("Image size (width, height):", img.size)
print("Image mode:", img.mode)

from tensorflow.keras.preprocessing.image import ImageDataGenerator
IMG_HEIGHT = 224
IMG_WIDTH = 224
BATCH_SIZE = 32

train_datagen = ImageDataGenerator(
    rescale=1./255,          # normalize
    validation_split=0.2,    # 80% train, 20% validation
    rotation_range=20,
    width_shift_range=0.2,
    height_shift_range=0.2,
    zoom_range=0.2,
    horizontal_flip=True
)
val_datagen = ImageDataGenerator(
    rescale=1./255,
    validation_split=0.2
)

train_generator = train_datagen.flow_from_directory(
    DATASET_PATH,
    target_size=(IMG_HEIGHT, IMG_WIDTH),
    batch_size=BATCH_SIZE,
    class_mode='categorical',
    subset='training'
)

validation_generator = val_datagen.flow_from_directory(
    DATASET_PATH,
    target_size=(IMG_HEIGHT, IMG_WIDTH),
    batch_size=BATCH_SIZE,
    class_mode='categorical',
    subset='validation'
)

print(train_generator.class_indices)

batch_x, batch_y = next(train_generator)
print("Image batch shape:", batch_x.shape)
print("Label batch shape:", batch_y.shape)

print("Min pixel value:", batch_x.min())
print("Max pixel value:", batch_x.max())

train_generator.class_indices

print("Training samples:", train_generator.samples)
print("Validation samples:", validation_generator.samples)

from tensorflow.keras.applications import ResNet50
from tensorflow.keras.models import Model
from tensorflow.keras.layers import Dense, GlobalAveragePooling2D, Dropout
from tensorflow.keras.optimizers import Adam

base_model = ResNet50(
    weights='imagenet',
    include_top=False,
    input_shape=(224, 224, 3)
)
# freeze layers
for layer in base_model.layers:
    layer.trainable = False

x = base_model.output
x = GlobalAveragePooling2D()(x)
x = Dense(256, activation='relu')(x)
x = Dropout(0.5)(x)

output = Dense(
    train_generator.num_classes,
    activation='softmax'
)(x)
model = Model(inputs=base_model.input, outputs=output)
model.compile(
    optimizer=Adam(learning_rate=0.0001),
    loss='categorical_crossentropy',
    metrics=['accuracy']
)
model.summary()

from tensorflow.keras.callbacks import ModelCheckpoint

checkpoint = ModelCheckpoint(
    "best_model.keras",          # new recommended format
    monitor="val_accuracy",
    save_best_only=True,
    mode="max",
    verbose=1
)
checkpoint_all = ModelCheckpoint(
    "model_epoch_{epoch:02d}.keras",
    save_best_only=False,
    verbose=0
)
EPOCHS = 20

history = model.fit(
    train_generator,
    validation_data=validation_generator,
    epochs=EPOCHS,
    callbacks=[checkpoint, checkpoint_all]
)

val_loss, val_accuracy = model.evaluate(validation_generator)
print("Validation Accuracy:", val_accuracy)
print("Validation Loss:", val_loss)

from tensorflow.keras.models import load_model
from tensorflow.keras.callbacks import ModelCheckpoint

model = load_model("/content/drive/MyDrive/plant_disease/best_model.keras")

checkpoint = ModelCheckpoint(
    "best_model.keras",          # new recommended format
    monitor="val_accuracy",
    save_best_only=True,
    mode="max",
    verbose=1
)

EPOCHS=10
history = model.fit(
    train_generator,
    validation_data=validation_generator,
    epochs=EPOCHS,
    callbacks=[checkpoint]
)

import matplotlib.pyplot as plt

plt.figure(figsize=(12,5))

plt.subplot(1,2,1)
plt.plot(history.history['accuracy'], label='Train')
plt.plot(history.history['val_accuracy'], label='Validation')
plt.title("Accuracy")
plt.legend()

plt.subplot(1,2,2)
plt.plot(history.history['loss'], label='Train')
plt.plot(history.history['val_loss'], label='Validation')
plt.title("Loss")
plt.legend()

plt.show()

for layer in model.layers[-30:]:
    layer.trainable = True
from tensorflow.keras.optimizers import Adam

model.compile(
    optimizer=Adam(learning_rate=1e-5),
    loss="categorical_crossentropy",
    metrics=["accuracy"]
)
from tensorflow.keras.callbacks import EarlyStopping

early_stop = EarlyStopping(
    monitor="val_loss",
    patience=5,
    restore_best_weights=True
)
history = model.fit(
    train_generator,
    validation_data=validation_generator,
    epochs=10,
    callbacks=[checkpoint, early_stop]
)

from tensorflow.keras.callbacks import ModelCheckpoint, EarlyStopping
from tensorflow.keras.optimizers import Adam

# Freeze base model layers (if using ResNet as base_model)
for layer in base_model.layers:
    layer.trainable = False

model.compile(
    optimizer=Adam(learning_rate=1e-4),
    loss="categorical_crossentropy",
    metrics=["accuracy"]
)

checkpoint = ModelCheckpoint(
    "best_model.keras",
    monitor="val_accuracy",
    save_best_only=True,
    mode="max",
    verbose=1
)

early_stop = EarlyStopping(
    monitor="val_loss",
    patience=5,
    restore_best_weights=True
)

history_initial = model.fit(
    train_generator,
    validation_data=validation_generator,
    epochs=10,
    callbacks=[checkpoint, early_stop]
)

history_initial = model.fit(
    train_generator,
    validation_data=validation_generator,
    epochs=10,
    callbacks=[checkpoint, early_stop]
)

from tensorflow.keras.callbacks import ModelCheckpoint, EarlyStopping
from tensorflow.keras.optimizers import Adam


# Unfreeze last 30 layers of base model ONLY
for layer in base_model.layers[-30:]:
    layer.trainable = True

model.compile(
    optimizer=Adam(learning_rate=1e-5),  # smaller LR
    loss="categorical_crossentropy",
    metrics=["accuracy"]
)

history_fine = model.fit(
    train_generator,
    validation_data=validation_generator,
    epochs=20,
    callbacks=[checkpoint, early_stop]
)

